metabrainz/bookbrainz-data-js

index.js
models/creatorType.js
models/editionFormat.js
models/editionStatus.js
models/entities/creator.js
models/entities/creatorData.js
models/entities/edition.js
models/entities/publication.js
models/entities/publisher.js
models/entities/work.js
models/entity.js
models/entityData.js
models/entityRevision.js
models/publicationType.js
models/publisherType.js
models/workType.js
package.json
test/testEntity.js
test/testEntityRevision.js

This removes the current custom methods for insert, update and delete and relation-based fetching of data in favor of using views defined in SQL which automatically do the right thing when passed a composed entity object.
Basic read testing has been done, with insert/update/delete testing done at the SQL level only. Also missing unit tests for the moment.

Use SQL-based views for entity CRUD

---

models/data/editionData.js
models/data/publicationData.js
models/data/publisherData.js
models/data/workData.js
models/entities/creator.js
models/entities/edition.js
models/entities/publication.js
models/entities/publisher.js
models/entities/work.js
models/languageSet.js
models/publisherSet.js
models/releaseEventSet.js
models/revisions/editionRevision.js
models/revisions/workRevision.js

This pulls in the schema changes in https://github.com/bookbrainz/bookbrainz-sql/pull/2, provides models for them, and uses those models in building relations on Edition and Work entities.

Hook in modified schema for edition/work properties

---

test/testAchievementUnlock.js
test/testAnnotation.js
test/testCreator.js
test/testEdition.js
test/testEditionRevision.js
test/testEditor.js
test/testEditorEntityVisits.js
test/testPublication.js
test/testPublisher.js
test/testRevision.js
test/testTitleUnlock.js
test/testWork.js

The `Editor` table no longer has a password field, but tests depending on having an editor in the database still attempt to create one, and the `Editor` model tests still test for password behavior. This breaks CI.

Fix tests depending on Editor password

---

models/data/creatorData.js
models/data/publisherData.js
models/editor.js

This PR adds area relations to the following bookshelf entity models:
- Editor
- Creator
- Publisher
Following this change, UI for editing these area fields will be exposed on the bookbrainz site.

Added area relations to Editor, Creator, and Publisher entity models

---

package.json

eslint-plugin-flowtype 2.50.1 seemed not to pass build, but 2.50.0 does.

chore(greenkeeper): pin eslint-plugin-flowtype to 2.50.0

---

src/func/entity.js

To have a display name for deleted entities on the entity display page

Fetch entity's last known default alias from its revision parent

---

src/models/entities/edition.js
src/util.js
test/testEdition.js

Upon creation for Editions that do not have an editionGroupBbid set.
If updating an existing Edition, unsetting editionGroupBbid will throw an error (transactions will roll back)
Also added accompanying test for both cases

Create edition group automatically

---

src/func/entity.js
test/func/entity.js

Creates a `recursivelyGetRedirectBBID` method and uses it in `getEntity`.
A simple recursive lookup on the `entity_redirect` table.
This step is necessary for entity merging.

Implement Entity redirection

---

src/util.js
test/util.js

No ambiguity for negative/positive years
eg: +002019-01-01, -000100

feat(bc-dates): formatDate returns full ISO 8601-2004 date

---

package-lock.json
package.json
src/func/author-credit.js
src/index.js
test/func/alias.js
test/func/author-credit.js
test/func/identifier.js
test/func/relationship.js
test/func/set.js

Update BookshelfJS to version 1.x (from 0.15.x), and resolve high severity vulnerability with Knex (See #199 ).
Following the update, a small change is required in the bookbrainz-site repo (in the [awardUnlock function](https://github.com/bookbrainz/bookbrainz-site/blob/07fd0f62bda21146d466c7fbcc06e20bcd10237c/src/server/helpers/achievement.js#L42-L55)), following some changes with the `fetch()` method:
https://github.com/bookshelf/bookshelf/wiki/Migrating-from-0.15.1-to-1.0.0#default-to-require-true-on-modelfetch-and-collectionfetchone

chore: Update Bookshelf and Knex ORM

---

src/func/entity.js

For the `/merge` route, when calling getEntityByBBID we want to get the final redirected BBID.
With this PR, we can call  recursivelyGetRedirectBBID with a knex/bookshelf transaction object.

feat(merge-tool): Allow passing transaction to recursivelyGetRedirectBBID

---

src/func/entity-sets.js
src/func/relationship.js
src/models/data/publisherData.js
src/models/revisions/authorRevision.js
src/models/revisions/editionGroupRevision.js
src/models/revisions/editionRevision.js
src/models/revisions/publisherRevision.js
src/models/revisions/workRevision.js
src/util.js

After v1.x update (PR #200 ), require is the default fetch option and exceptions are thrown in places they shouldn't.

Fix(update-bookshelf): Set 'require' fetch option to false where needed

---

src/func/releaseEvent.js

in updateReleaseEventSet.
The issue appeared in https://github.com/bookbrainz/bookbrainz-site/pull/342 .
If one areaId is null and the other undefined, they are currently considered not equal.
Broaden the scope and consider nil values equal.

fix(ReleaseEvents): Consider null and undefined areas equal

---

src/util.js
test/util.js

Condition for year = 0 was not properly handled. Added an and condition

BB-434 fix: allow year=0 in ISO date parsing

---

src/models/revisions/authorRevision.js
src/models/revisions/editionGroupRevision.js
src/models/revisions/editionRevision.js
src/models/revisions/publisherRevision.js
src/models/revisions/workRevision.js

`parent` function inside the `EntityRevision` was giving the wrong parent in some cases.
This PR fixes that.

fix(parent-revision): return the correct parent revision

---

src/models/revisions/editionRevision.js

Add authorCredits and their names to the list of properties to compare when doing a revision diff.

feat(diffs): Diff authorCredits when present

---

src/models/entities/edition.js
src/util.js
test/testEdition.js

When an Edition is saved without an Edition Group, a new EG is automatically created.
This PR adds the authorCreditId from the Edition to those auto-created EGs
Depends on https://github.com/bookbrainz/bookbrainz-site/pull/557

feat(AC): Add Author Credit id to auto-created Edition Groups

---

src/func/index.ts
src/func/work.ts

Moved the contents of the function ``loadWorkTableAuthors`` in this [PR](https://github.com/metabrainz/bookbrainz-site/pull/617), to ``src/func/work.ts``.
After loading all the relationships of an edition, the relationships with ``typeId=10`` (Edition contains Work), will be sent to this function. This function will then load the relationshipSet of the Work. From these, it will filter the relationship with ``typeId=8 ``(Author wrote work), to extract the author and then load its defaultAlias and add it to the object.

FEAT[BB-281]: Function to load the Authors of works in an edition

---

src/func/externalServiceOauth.ts
src/func/index.ts
src/func/types.ts
src/index.ts
src/models/externalServiceOauth.js
test/func/externalServiceOauth.js
test/testExternalServiceOauth.js

This PR adds the following:
1. A model for the `external_service_oauth` table.
2. Functions for fetching, saving, updating and deleting Oauth tokens in the database.

feat: add externalServiceOauth table and functions

---

src/models/authorCredit.js

To support fetching all editions related to a author credit.
reference ticket: -
[BB-288](https://tickets.metabrainz.org/browse/BB-288): List publications / editions for creators

Feat: Add editions relation in AuthorCredit model

---

.github/workflows/jsdoc-gh-pages.yml
.vscode/tasks.json
package.json

I broke the JSDoc workflow with #297, fixing it now by adding the step to build the project's JS before running the JSDoc build

chore: Github workflow: fix JSDoc building action

---

.github/workflows/ci.yml
README.md
package.json
src/func/types.ts
yarn.lock

[SEC-999](https://tickets.metabrainz.org/browse/SEC-999) / [BB-731](https://tickets.metabrainz.org/browse/BB-731):
Bookshelf is apparently unmaintained (https://github.com/bookshelf/bookshelf/issues/2121) and enforces us to use a horribly outdated knex version <0.22!
- Use our own fork with updated dependencies:
https://github.com/bookbrainz/bookshelf/pull/1
- The only breaking change seems to be a Knex type import which I had to change, my development server is still working using this branch (via `yarn link`) and the test suite is still passing*.
*) As of 2023-03-17, the test suite is passing in CI and locally, although the latter wasn't always the case when I ran the tests repeatedly on 16th.
<details>
<summary>Older observations</summary>
*) Well, almost. The first time all 160 test …

BB-731: Update knex to v2.4.2

---

src/func/alias.ts
src/func/entity.ts
src/func/imports/recent-imports.ts
src/func/relationship.ts
src/func/types.ts
src/types/aliases.ts
src/types/entity.ts
src/types/identifiers.ts
src/types/language.ts
src/types/utils.ts

Incomplete type definitions for entities with aliases and identifiers which were written for https://github.com/metabrainz/bookbrainz-site/pull/943 and could be used in other places too.
As long as the data models themselves are untyped, it helps to have at least some basic, separate type definitions for certain parts which are defined in a central place. They can be expanded as needed until the models have been migrated to a type-safe ORM ([BB-729](https://tickets.metabrainz.org/browse/BB-729)).
It should be trivial to integrate these provisional type definitions into the new models then.

Minimal entity typings (aliases and identifiers)

---

test/testEditor.js

The 'privs' column was added in https://github.com/metabrainz/bookbrainz-site/pull/993 and merged into bookbrainz-site master branch in https://github.com/metabrainz/bookbrainz-site/pull/1020
This causes the testEditor test to fail with an unexpected key in the Editor model JSON.

Add 'privs' key to expected Editor model output

---

.babelrc
.github/workflows/ci.yml
README.md
package.json

Minimal version supported, now that Node 16 is end-of-life.
See also https://github.com/metabrainz/bookbrainz-site/pull/1016

chore: Update Node version to 18

---

package.json
src/func/author-credit.ts
src/func/editor.ts
src/func/imports/create-import.ts
src/types/imports.ts
yarn.lock

Existing imports can now be updated if they are still pending. The implementation currently only overwrites the import header to link to the freshly created entity data and leaves all the old entity data behind orphaned. (Still to be improved...)
I've also made the options parameter more flexible to already include support for creating updates for accepted entities as well (which might be added in a future version.) In addition to the import ID, the `createImport` function now also returns its status (which is used by the consumer).
Also contains a few more fixes for type errors (in currently unused code) which I somehow had not seen so far.

Repeatable imports

---

src/models/entities/edition.ts
src/util.ts

BB-768
**Part of [PR 1051](https://github.com/metabrainz/bookbrainz-site/pull/1051) in bookbrainz-site repo**
- **Part of [PR 1051](https://github.com/metabrainz/bookbrainz-site/pull/1051)**
added new creditSection argument and made some changes in `autoCreateNewEditionGroup` and `createEditionGroupForNewEdition` functions so the new auto created edition group get saved with the same state of credit section as of the edition it is created for
honestly I did not know how can i test these changes with bookbrainz-site , maybe creating my own package and copy the content with my changes from this and changing the links and package name to my npm package in package.json in bookbrainz-site, but as the changes were very small and simple this may just work 😶 
edition model

part of issue BB-768 : updating the edition model function

---

package.json
src/func/author.ts
src/func/date.ts
src/util.ts
src/validators/author.ts
src/validators/base.ts
src/validators/common.ts
src/validators/date.js
src/validators/date.ts
src/validators/edition-group.ts
src/validators/edition.ts
src/validators/publisher.ts
src/validators/series.ts
src/validators/work.ts
test/validators/data.js
test/validators/helpers.js
test/validators/test-alias.js
test/validators/test-author.js
test/validators/test-edition-group.js
test/validators/test-edition.js
test/validators/test-identifier.js
test/validators/test-name-section.js
test/validators/test-publisher.js
test/validators/test-series.js
test/validators/test-submission-section.js
test/validators/test-work.js
yarn.lock

We have two nearly duplicate sets of entity validation functions in [`bookbrainz-site`](https://github.com/metabrainz/bookbrainz-site/tree/2315cb7707a31dc096758c03d7df128f15588d1e/src/client/entity-editor/validators) and [`bookbrainz-utils`](https://github.com/metabrainz/bookbrainz-utils/tree/421cbc9e9783ca5e957b6291efa378e2a3519bd8/importer/src/consumer/validators) which should ideally be part of `bookbrainz-data` and then can be used by both.
- Copy the validators and their tests from `bookbrainz-site` into this repository and make sure the tests still pass (`yarn build-js-for-test && mocha test/validators`).
- Refactor validators to throw a `ValidationError` with the reason instead of just a boolean.
- Adapt tests to expect errors. (Luckily this was mostly a search and replace job with …

Unify entity validators

---

src/validators/edition-group.ts
src/validators/edition.ts

Following from #316 we saw a failing build caused by a type issue with the author credit section Immutable Iterable type, specifically its size property
I will note that the Immutable types have this to say about `size`:

Fix type of author credit size in validators

---

src/func/create-entity.ts
src/func/imports/approve-import.ts

Approving imported entities currently fails on https://github.com/metabrainz/bookbrainz-site/commit/66845752f6a5b09bdc13bb8b3cb582ef139b03e4
- Avoid SQL errors for direct approval (`approveImport`) and the edit and approve workflow (`createEntity`)
- Return the full Bookshelf model which is needed for search indexing in https://github.com/metabrainz/bookbrainz-site/pull/1103
Only import related ORM functions are affected this time.
Doing an npm an release is not required yet, there will be more changes soon and I am using a local version of the ORM package anyway.

Make approval of imported entities work

---

src/func/annotation.ts
src/func/imports/create-import.ts
src/types/parser.ts
src/validators/author.ts
src/validators/common.ts
src/validators/edition-group.ts
src/validators/edition.ts
src/validators/publisher.ts
src/validators/series.ts
src/validators/work.ts
test/validators/data.js
test/validators/test-annotation-section.js

Annotations are not implemented for imported entities, because they have a `last_revision_id INT NOT NULL` column. Since an import does not have a revision, it is not possible to create a valid annotation row for it.
Actually use the given annotation data from the queued entity and insert it into the database with `last_revision_id = NULL`.
Before this code is usable, we have to make `annotation.last_revision_id` nullable in the schema and
in the code of `bookbrainz-site`.
P.S. Also sneaking in a minor DX QoL change with a032186.

Support annotations for imported entities

---

package.json
yarn.lock

Fixes https://github.com/metabrainz/bookbrainz-data-js/security/dependabot/42

chore: Upgrade mocha to v11
