- models/editor.js
Adds titleUnlock to the available methods in the editor model
> Add titleUnlock to editor methods

- models/area.js
- test/testArea.js
To make Area model seem more similar to indexed entity models.
> Added virtual bbid property to Area model

- models/revisions/creatorRevision.js
- models/revisions/publisherRevision.js
Required for area changes to be displayed in revisions
> Included area in relations fetched for diff field in Publisher and Creator

- src/func/editor.js
- src/func/index.js
This PR introduces a deleteEditorByMetaBrainzID function to support https://github.com/bookbrainz/bookbrainz-site/pull/196
> feat(func): add function to delete editor by MetaBrainz ID

- src/func/alias.js
- src/func/entity.js
Helper functions to find alias with matching names.
> Add functions to check if alias already exists

- src/func/alias.js
- src/func/entity.js
- src/func/imports/create-import.js
- src/func/imports/delete-import.js
- src/func/imports/recent-imports.js
Use lodash's snakeCase method to turn EditionGroup into edition_group instead of editiongroup
> fix: Correct case for entity table names 

- src/util.js
- test/util.js
This is part of the fix for [BB-324](https://tickets.metabrainz.org/browse/BB-324)
> Allow BCE dates (negative years)

- src/func/alias.js
- test/func/alias.js
This patch ensures that only one alias is set to 'primary' for each language.
The default alias is always considered primary, setting any other alias for the same language to non-primary.
If there already is a non-default primary alias for that language, keep that one and set the others to non-primary.
If there are multiple new primary aliases for a language in an edit, allow only the first one to be primary.
> fix(BB-158): Allow only one primary alias per language

- src/index.js
- src/models/editor.js
- src/models/userCollection.js
- src/models/userCollectionCollaborator.js
- src/models/userCollectionItem.js
> models : add userCollection models

- src/models/userCollectionCollaborator.js
`UserCollectionCollaborator` model have to be updated due to changes in DB
https://github.com/bookbrainz/bookbrainz-site/pull/451
> refactor: change editor_id-->collaborator_id

- src/models/entities/edition.js
- test/testEdition.js
Previously, an EG would be created automatically if a *new* Edition was created without an EG selected.
This PRs adds the possibility for an *existing* Edition edit to remove the previously selected EG and auto create a new one.
See https://github.com/bookbrainz/bookbrainz-site/pull/522 and https://tickets.metabrainz.org/browse/BB-537 for context
> feat(edition): Allow Edition Groups to be auto-created if editing an existing Edition

- package-lock.json
- package.json
Upgrades node-postgres package to adapt to the new Node LTS version (14).
> fix(CI): Update postgres node package

- src/func/area.js
- src/func/index.js
- src/index.js
- src/models/area.js
- src/models/areaType.js
- test/func/area.js
- test/testArea.js
Adding an AreaType model and a function to recursively get an Area's parent (using l_area_area table from musicbrainz)
> New models and helpers for Area entities

- README.md
Updated [README.md](https://github.com/bookbrainz/bookbrainz-data-js/blob/master/README.md) with correct filename.
> FIX(docs): Incorrect FileName in README

- .github/PULL_REQUEST_TEMPLATE.md
Add a pull request template.
Comes in handy to guide contributors to fill PR descriptions to the point.
> chore : added PULL_REQUEST_TEMPLATE

- src/models/entities/author.js
- src/models/entities/edition.js
- src/models/entities/editionGroup.js
- src/models/entities/publisher.js
- src/models/entities/work.js
- test/testAuthor.js
- test/testEdition.js
- test/testEditionGroup.js
- test/testPublisher.js
- test/testWork.js
This PR Fixes : [BB-614](https://tickets.metabrainz.org/projects/BB/issues/BB-614?filter=allissues)
Follow up from PR : [#599](https://github.com/bookbrainz/bookbrainz-site/pull/599)
Added `collections()` to all the **Entity Model**. This helps to fetch all the collections **related** to the entity.
Also added the corresponding **tests** for it.
- [models/entities/author.js](https://github.com/bookbrainz/bookbrainz-data-js/blob/master/src/models/entities/author.js)
- [models/entities/work.js](https://github.com/bookbrainz/bookbrainz-data-js/blob/master/src/models/entities/work.js)
- [models/entities/edition.js](https://github.com/bookbrainz/bookbrainz-data-js/blob/master/src/models/entities/edition.js)
- [models/entities/editionGroup.js](https://github.com/bookbrainz/bookbrainz-data-js/blo …
> feat(collections): Get all the collections related to a Entity

- test/func/language.js
- test/testLanguageSet.js
Tests for languageSet Model was missing
Added Tests for languageSet Model
> test: added tests for languageSet Model

- test/testAuthorRevision.js
Tests for AuthorRevision Model was missing
Added basic tests for AuthorRevision model
/test
> test: Added basic tests for AuthorRevision model

- test/testEditionGroupRevision.js
Tests for EditionGroupRevision Model was missing
Added basic tests for EditionGroupRevision model
/test
> test: Added basic tests for EditionGroupRevision model

- test/testWorkRevision.js
Tests for WorkRevision Model was missing
Added basic tests for WorkRevision Model
/test
> test: Added tests for WorkRevision Model

- test/testPublisherRevision.js
Tests for PublisherRevision Model was missing
Added basic tests for PublisherRevision Model
/test
> test: Added basic tests for PublisherRevision Model

- src/models/revisions/authorRevision.js
- src/models/revisions/editionGroupRevision.js
- src/models/revisions/editionRevision.js
- src/models/revisions/publisherRevision.js
- src/models/revisions/seriesRevision.js
- src/models/revisions/workRevision.js
Added relationship attributes to diff revision.
> feat: add relationship attributes to diffRevisions

- test/func/work.js
First creating a work entity in the createWork function.
Then creating an alias for the author entity.
Then in the createRelationshipSet function, I have created an author and then trying to link it into the relationshipSet of the work entity.
> test(loadAuthorNames): Test for the loadAuthorNames func

- src/index.ts
- src/models/collectionSubscription.js
- src/models/entitySubscription.js
- src/models/notification.js
Adding models for newly created table for Notification feature
> add models for new tables for notification service

- src/func/relationship.ts
- test/func/relationship.js
Ticket [BB-538](https://tickets.metabrainz.org/browse/BB-538)
This PR is for supporting workflow as describe [here](https://github.com/metabrainz/bookbrainz-site/pull/876)
> Fix(BB-538): Support concurrent relationships edit workflow

- .github/workflows/ci.yml
- .github/workflows/test-report.yml
- package.json
- test/bookshelf.js.example
- test/func/entity.js
- test/testAuthor.js
- test/testEdition.js
- test/testEditionGroup.js
- test/testPublisher.js
- test/testSeries.js
- test/testWork.js
> chore: Run CI tests in Github

- .github/release-drafter.yml
- .github/workflows/draft-release.yml
Simplify the process of having clean releases with this automated release drafter, like we have in bookbrainz-site. Template config copied from the same
> chore: add release drafter workflow

- src/index.ts
- src/models/adminLog.js
Created a corresponding model for ``bookbrainz.admin_log`` table.
> feat(Admin-logs): AdminLog Model
